language: python
python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'pypy'
  - 'pypy3'
install:
  - pip install -e .
    # python-coveralls requires coverage 3.
    # See https://github.com/z4r/python-coveralls/pull/41
  - pip install coverage==3.7.1
  - pip install -r requirements.txt
script:
  - python setup.py test
after_success:
  - coveralls
